### PR TITLE
added utils for json responses

### PR DESCRIPTION
**Pull request by facundoolano**
This adds `json` and `sorted-json` to macchiato.util.responses. I've found those functions handy when dealing with JSON API handlers.

### CODE REVIEW

**Comment by yogthos** [comment]
Might make sense to add transit as well, as EDN is pretty common for Clojure client/server communication.

**Comment by yogthos** [comment]
excellent, I'll push out the new version

**Comment by facundoolano** [comment]
cool!

**Comment by yogthos** [comment]
@facundoolano  Also, I completely forgot to mention the [restful-format](https://github.com/macchiato-framework/macchiato-core/blob/master/src/macchiato/middleware/restful_format.cljs) middleware is probably the best way to handle encoding/decoding in most situations. It attempts to figure out the content type based on the header, and encodes the response based on the accept types provided. I haven't had a chance to test it too much yet, but if you can take it for a spin that would be great. :)

**Comment by facundoolano** [comment]
Yeah, I've tried it when I was just starting out with my experiments, and it didn't work exactly as I needed at the time (I don't exactly remember what it was, I think that it had to do with it not parsing the body if there wasn't an accept header present). I should probably revisit now that I have a better idea of how the pieces fit together.

**Comment by yogthos** [comment]
Yeah, I definitely don't rule out bugs there either. I'm just starting to make an API in a project at work, so I'll end up dogfooding it shortly. :)

**Pull request merged**
