### PR TITLE
Add optional transit configuration

### PR DESCRIPTION
**Pull request by usernolan**
Wanted to get feedback before adding additional tests, renaming `restul_format.cljs -> restful_format.cljs`, aligning the formatting, etc.

### CODE REVIEW

**Comment by yogthos** [comment]
That looks great to me. I'm happy with the formatting, I tend to align things vertically as well. Good catch on the typo in the namespace name. :)

**Comment by Nolan330** [comment]
Right on, appreciate the feedback. Will check through and add some more meaningful tests later in the week.

**Comment by usernolan** [comment]
Right on, appreciate the feedback. Will check through and add some more meaningful tests later in the week.

**Comment by yogthos** [comment]
and I'm happy to merge and push out an update if things look good to you

**Comment by usernolan** [comment]
Yeah if it checks out with you, it looks good to me! It's a simple change after all. I'll open up a new PR if I stumble into any premium improvements as I work with it more 👍.

Thanks again for all your work on this epic tool.

**Comment by yogthos** [comment]
And new version is up on Clojars, thanks again for a great PR. :)

**Pull request merged**
